services:
  django:
    build:
      context: "."
    container_name: django
    command: bash -c "./manage.py migrate && ./manage.py loaddata db.json && ./manage.py runserver 0.0.0.0:8000"
    # disable restart to avoid autostart containers on boot
    restart: no
    # volume used to hot reload changes
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      SECRET_KEY: ${DJANGO_SECRET_KEY}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

  tailwind:
    build:
      context: "."
    container_name: tailwind
    volumes:
      - .:/app
    restart: no
    #command: bash -c "./manage.py tailwind install --no-input && ./manage.py tailwind build --no-input && ./manage.py collectstatic --no-input && ./manage.py tailwind start"
    command: bash -c "./manage.py tailwind install --no-input && ./manage.py tailwind start"
    # Without tty, no stdin, and tailwind watcher aborts
    # https://github.com/tailwindlabs/tailwindcss/issues/5324
    tty: true
    stop_grace_period: 1s  # SIGKILL after 1s

  db:
    image: postgres:16.2
    container_name: db
    # disable restart to avoid autostart containers on boot
    restart: no
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${DB_NAME} 
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      #PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:5432"
    # ENABLE IN PRODUCTION
    # volumes:
      # - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    container_name: adminer
    # disable restart to avoid autostart containers on boot
    restart: no
    ports:
      - "8080:8080"

# ENABLE IN PRODUCTION
# volumes:
  # pgdata:
