FROM ubuntu:latest

WORKDIR /app

# install culr
RUN apt-get -y update
RUN apt-get -y install curl

# Add standalone TailwindCSS CLI binary to /usr/local/bin (path)
RUN curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
RUN mv tailwindcss-linux-x64 tailwindcss
RUN chmod +x tailwindcss
RUN cp tailwindcss /usr/local/bin/

ENTRYPOINT ["tailwindcss"]
CMD ["-i", "static/css/tailwind.css", "-o", "static/css/base.min.css", "--minify", "--watch"]
