# Generated by Django 5.1.3 on 2024-12-17 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PP', 'In attesa di pagamento'), ('PR', 'In elaborazione'), ('SP', 'Spedito'), ('DL', 'Consegnato'), ('CN', 'Annullato'), ('RT', 'Restituito'), ('FL', 'Fallito')], default='PR', max_length=2),
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RQ', 'Richiesto'), ('AP', 'Approvato'), ('RJ', 'Rifiutato'), ('SH', 'Spedito'), ('IT', 'In Transito'), ('RC', 'Ricevuto'), ('IS', 'In Fase di Ispezione'), ('AC', 'Accettato'), ('RI', 'Rimborso Avviato'), ('RF', 'Rimborso Completato'), ('CL', 'Reso Chiuso')], default='RQ', max_length=2)),
                ('reason', models.CharField(choices=[('DF', 'Fallato o Danneggiato'), ('WI', 'Prodotto sbagliato'), ('NN', 'Non serve più'), ('SI', 'Problemi di taglia o vestibilità'), ('ND', 'Diverso dalla descrizione'), ('BP', 'Trovato ad un prezzo migliore'), ('OM', 'Ordinato per errore'), ('OT', 'Altro motivo')], max_length=2)),
                ('comments', models.CharField(max_length=200)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='orders.orderitem')),
            ],
        ),
    ]
