# Generated by Django 5.1.3 on 2024-11-17 23:43

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='order',
            name='address_line_one',
            field=models.CharField(default='Via Roma 12', max_length=40, verbose_name='Riga Indirizzo 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='address_line_two',
            field=models.CharField(default='Interno 27', max_length=40, verbose_name='Riga Indirizzo 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Roma', max_length=40, verbose_name='city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='Pinco Pallino', max_length=40, verbose_name='Nome completo (nome e cognome)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='0123456789', max_length=128, region='IT', verbose_name='Numero di telefono'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default='00100', max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]{5}$', 'CAP non valido, inserisci 5 numeri')], verbose_name='CAP'),
            preserve_default=False,
        ),
    ]
