# Generated by Django 5.1.3 on 2024-12-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CS', 'Contrassegno'), ('PP', 'Paypal'), ('SP', 'Stripe')], default=None, max_length=2),
        ),
    ]
