# Generated by Django 5.1.3 on 2024-12-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_payment_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PP', 'In attesa di pagamento'), ('PR', 'In elaborazione'), ('SP', 'Spedito'), ('DL', 'Consegnato'), ('CN', 'Annullato'), ('FL', 'Fallito')], default='PR', max_length=2),
        ),
    ]
