# Generated by Django 5.1.3 on 2024-11-23 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='vote',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
