# Generated by Django 5.1.1 on 2024-10-10 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
