# Generated by Django 5.1.1 on 2024-10-16 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent_category',
            new_name='parent',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent', 'name')},
        ),
    ]
