# Generated by Django 5.1.1 on 2024-10-17 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='is_active',
        ),
    ]
