# Generated by Django 5.1.2 on 2024-10-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_productvariant_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='size',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
