# Generated by Django 5.1.2 on 2024-10-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_size_options_size_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
