# Generated by Django 5.1.2 on 2024-10-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_category_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['position', 'name'], 'verbose_name_plural': 'Categories'},
        ),
    ]
