# Generated by Django 5.1.3 on 2024-11-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_productimage_unique_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='productcolor',
            constraint=models.UniqueConstraint(condition=models.Q(('default', True)), fields=('product',), name='one_default_product_color_for_product'),
        ),
    ]
