# Generated by Django 5.1.2 on 2024-10-17 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['position'], 'verbose_name_plural': 'Categories'},
        ),
    ]
