# Generated by Django 5.1.3 on 2024-11-25 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productcolor_price_productvariant_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='percentage',
            field=models.PositiveIntegerField(verbose_name=django.core.validators.MaxValueValidator(100)),
        ),
    ]
