# Generated by Django 5.1.3 on 2024-12-02 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_discount_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='last_modification',
            new_name='updated_at',
        ),
    ]
