# Generated by Django 5.1.3 on 2024-12-06 10:18

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_rename_date_created_product_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['-hex']},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='customer',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('product', 'user')},
        ),
    ]
