# Generated by Django 5.1.2 on 2024-10-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_size_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
