# Generated by Django 5.1.2 on 2024-10-18 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_category_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='position',
        ),
    ]
